name: Java Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Schritt 1: Code auschecken
    - name: Check out code
      uses: actions/checkout@v3

    # Schritt 2: JDK 20 (Corretto) einrichten
    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'corretto'

    # Schritt 3: Gradle ausführen und Tests ausführen
    - name: Build and test with Gradle
      run: |
        ./gradlew clean test
