name: Java Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 20 (Corretto)
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'corretto'

      - name: Build and test with Gradle
        run: |
          ./gradlew clean test
